### ISSUE TITLE
Bill printing by Clients

### ISSUE THREAD

**Issue by pasyangtan** [pasyangtan/WaterBillingSystem#10]
In client login, they should only view their bill details but in the system, they can also print their own bill.
![issue tracking 2](https://user-images.githubusercontent.com/101698260/168541136-c4ffe967-94b6-497c-b680-b275c8ec277c.png)
![issue tracking 1](https://user-images.githubusercontent.com/101698260/168541142-283c709a-94eb-4c73-841a-34dc2cb3a999.png)

**Comment by Sameersth015** [comment]
It isn't really an issue. There is a bill print option so that the customer can have a copy of the bill.
