### ISSUE TITLE
Login Page error

### ISSUE THREAD

**Issue by SthBishal** [pasyangtan/WaterBillingSystem#2]
![Capture](https://user-images.githubusercontent.com/101698265/162765123-1125a9a2-e3d5-4326-a86d-8c10fc215419.PNG)

It says that the arrays uname and pass are undefined. Please go through them.

**Comment by Sameersth015** [comment]
![login](https://user-images.githubusercontent.com/102210766/162767108-7c7d7e92-eb5f-4722-b2e0-e54d73ca69e4.jpg)
The issue is solved please check again and let me know if there is still an issue.
