### ISSUE TITLE
In the client page where there is bill view  there is black background in bill reading cannot be read properly.

### ISSUE THREAD

**Issue by SthBishal** [pasyangtan/WaterBillingSystem#3]
![issue 1](https://user-images.githubusercontent.com/101698265/168474076-c662ef7a-0751-400e-b3d7-8d9ba336c3e9.jpg)

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-08-30](https://user-images.githubusercontent.com/102210766/168475087-db431c36-28a0-4aef-ac12-229f6426856b.png)
There was a minor problem on the line 21 where background color was set to black which was causing hindrance in reading the bill details. I set it to another color which doesn't effect the visibility of details. You can have a look at it.

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-07-14](https://user-images.githubusercontent.com/102210766/168475194-fde39914-333a-491e-a08c-b8cd89fe5208.png)
![Screenshot from 2022-05-15 19-07-31](https://user-images.githubusercontent.com/102210766/168475198-b9e3c782-70be-434b-8083-5002b476f25c.png)

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-07-14](https://user-images.githubusercontent.com/102210766/168475212-1a412f49-fe3b-437c-8ae0-923f4d6f5c13.png)
![Screenshot from 2022-05-15 19-07-31](https://user-images.githubusercontent.com/102210766/168475214-66ff9213-d9bc-47f3-a185-a97fe0081d92.png)
