### ISSUE TITLE
In the admin clients page instead of showing System Clients it shows System Staffs

### ISSUE THREAD

**Issue by SthBishal** [pasyangtan/WaterBillingSystem#5]
![Screenshot (240)](https://user-images.githubusercontent.com/101698265/168475139-3aff350d-bb09-47a7-90f4-d497c6f6fb34.png)
@Sameersth015

**Comment by Sameersth015** [comment]
Ok that is a minor mistake i will correct that in a minute.

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-14-39](https://user-images.githubusercontent.com/102210766/168475379-d6249e17-86bd-4844-8dbb-9643387eeeb3.
![Screenshot from 2022-05-15 19-14-34](https://user-images.githubusercontent.com/102210766/168475397-03d30fe0-fa44-4cbf-b4f5-b69337cbaa4a.png)
png)
I see this is the problem in both admin and staff page.

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-16-25](https://user-images.githubusercontent.com/102210766/168475556-1c4af109-7c45-4e1c-9d95-de5ff73406a6.png)
![Screenshot from 2022-05-15 19-16-28](https://user-images.githubusercontent.com/102210766/168475559-312169e5-d3fb-448f-87ea-240ac00d1d03.png)
There was a typing mistake on clients.php file and eclients.php which lead to the above issue, it is solved now.
