### ISSUE TITLE
On the profile edit option on the client page the client can change their Meter Id by themselves

### ISSUE THREAD

**Issue by SthBishal** [pasyangtan/WaterBillingSystem#8]
![Screenshot (245)](https://user-images.githubusercontent.com/101698265/168477060-9e47e1ab-06a2-428f-a8c9-b940e68961a2.png)
@Sameersth015

**Comment by Sameersth015** [comment]
![image](https://user-images.githubusercontent.com/102210766/168478507-b8fbd0cb-72f5-42b7-a0d9-df47f1395bc5.png)
