### ISSUE TITLE
Error on the view bill page 

### ISSUE THREAD

**Issue by SthBishal** [pasyangtan/WaterBillingSystem#9]
![Screenshot (247)](https://user-images.githubusercontent.com/101698265/168477471-455c8aa3-b73c-4408-afae-8403f297bf89.png)
@Sameersth015

**Comment by Sameersth015** [comment]
![image](https://user-images.githubusercontent.com/102210766/168478463-4c796b7f-1225-481f-b0ea-b0925c51de8d.png)
